// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateURLRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateURLRecordRequest) Reset() {
	*x = CreateURLRecordRequest{}
	mi := &file_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateURLRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateURLRecordRequest) ProtoMessage() {}

func (x *CreateURLRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateURLRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateURLRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *CreateURLRecordRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateURLRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateURLRecordResponse) Reset() {
	*x = CreateURLRecordResponse{}
	mi := &file_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateURLRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateURLRecordResponse) ProtoMessage() {}

func (x *CreateURLRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateURLRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateURLRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateURLRecordResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CreateURLRecordBatchRequestItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CorrelationID is a unique identifier for this request, useful for matching
	// the response with the original request.
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// OriginalURL is the URL to be shortened.
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateURLRecordBatchRequestItem) Reset() {
	*x = CreateURLRecordBatchRequestItem{}
	mi := &file_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateURLRecordBatchRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateURLRecordBatchRequestItem) ProtoMessage() {}

func (x *CreateURLRecordBatchRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateURLRecordBatchRequestItem.ProtoReflect.Descriptor instead.
func (*CreateURLRecordBatchRequestItem) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *CreateURLRecordBatchRequestItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CreateURLRecordBatchRequestItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type CreateURLRecordBatchResponceItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CorrelationID matches the one sent in the corresponding BatchRequest.
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// ShortURL is the shortened version of the OriginalURL.
	ShortUrl      string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateURLRecordBatchResponceItem) Reset() {
	*x = CreateURLRecordBatchResponceItem{}
	mi := &file_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateURLRecordBatchResponceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateURLRecordBatchResponceItem) ProtoMessage() {}

func (x *CreateURLRecordBatchResponceItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateURLRecordBatchResponceItem.ProtoReflect.Descriptor instead.
func (*CreateURLRecordBatchResponceItem) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *CreateURLRecordBatchResponceItem) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CreateURLRecordBatchResponceItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type CreateURLRecordBatchRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Items         []*CreateURLRecordBatchRequestItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	UserId        string                             `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateURLRecordBatchRequest) Reset() {
	*x = CreateURLRecordBatchRequest{}
	mi := &file_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateURLRecordBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateURLRecordBatchRequest) ProtoMessage() {}

func (x *CreateURLRecordBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateURLRecordBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateURLRecordBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *CreateURLRecordBatchRequest) GetItems() []*CreateURLRecordBatchRequestItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateURLRecordBatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateURLRecordBatchResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Items         []*CreateURLRecordBatchResponceItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateURLRecordBatchResponse) Reset() {
	*x = CreateURLRecordBatchResponse{}
	mi := &file_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateURLRecordBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateURLRecordBatchResponse) ProtoMessage() {}

func (x *CreateURLRecordBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateURLRecordBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateURLRecordBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *CreateURLRecordBatchResponse) GetItems() []*CreateURLRecordBatchResponceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type URLRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // The unique identifier for the URL record
	Original      string                 `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`                     // The original URL before shortening
	Short         string                 `protobuf:"bytes,3,opt,name=short,proto3" json:"short,omitempty"`                           // The shortened URL
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // The ID of the user who created the shortened URL
	IsDeleted     bool                   `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"` // A flag indicating if the URL record is deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLRecord) Reset() {
	*x = URLRecord{}
	mi := &file_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLRecord) ProtoMessage() {}

func (x *URLRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLRecord.ProtoReflect.Descriptor instead.
func (*URLRecord) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *URLRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *URLRecord) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *URLRecord) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *URLRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *URLRecord) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type Short struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Short         string                 `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Short) Reset() {
	*x = Short{}
	mi := &file_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Short) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Short) ProtoMessage() {}

func (x *Short) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Short.ProtoReflect.Descriptor instead.
func (*Short) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *Short) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

type DeleteURLRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Short               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLRecordsRequest) Reset() {
	*x = DeleteURLRecordsRequest{}
	mi := &file_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLRecordsRequest) ProtoMessage() {}

func (x *DeleteURLRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLRecordsRequest.ProtoReflect.Descriptor instead.
func (*DeleteURLRecordsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteURLRecordsRequest) GetItems() []*Short {
	if x != nil {
		return x.Items
	}
	return nil
}

type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_proto_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *ID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ByUserID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OriginalURL is the original long-form URL.
	OriginalUrl string `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	// ShortURL is the shortened version of the original URL.
	ShortUrl      string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByUserID) Reset() {
	*x = ByUserID{}
	mi := &file_proto_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByUserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByUserID) ProtoMessage() {}

func (x *ByUserID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByUserID.ProtoReflect.Descriptor instead.
func (*ByUserID) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *ByUserID) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *ByUserID) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ByUserID            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByUserIDResponse) Reset() {
	*x = ByUserIDResponse{}
	mi := &file_proto_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByUserIDResponse) ProtoMessage() {}

func (x *ByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByUserIDResponse.ProtoReflect.Descriptor instead.
func (*ByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *ByUserIDResponse) GetItems() []*ByUserID {
	if x != nil {
		return x.Items
	}
	return nil
}

// StatsResponse represents responce for Stats handler
type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of shortened URLS
	Urls int32 `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	// Total number of users
	Users         int32 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *StatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *StatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_proto_shortener_proto protoreflect.FileDescriptor

const file_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shortener.proto\x12\tshortener\x1a\x1bgoogle/protobuf/empty.proto\"*\n" +
	"\x16CreateURLRecordRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"1\n" +
	"\x17CreateURLRecordResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"k\n" +
	"\x1fCreateURLRecordBatchRequestItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"f\n" +
	" CreateURLRecordBatchResponceItem\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"x\n" +
	"\x1bCreateURLRecordBatchRequest\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.shortener.CreateURLRecordBatchRequestItemR\x05items\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"a\n" +
	"\x1cCreateURLRecordBatchResponse\x12A\n" +
	"\x05items\x18\x01 \x03(\v2+.shortener.CreateURLRecordBatchResponceItemR\x05items\"\x85\x01\n" +
	"\tURLRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\boriginal\x18\x02 \x01(\tR\boriginal\x12\x14\n" +
	"\x05short\x18\x03 \x01(\tR\x05short\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x05 \x01(\bR\tisDeleted\"\x1d\n" +
	"\x05Short\x12\x14\n" +
	"\x05short\x18\x01 \x01(\tR\x05short\"A\n" +
	"\x17DeleteURLRecordsRequest\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.shortener.ShortR\x05items\"\x14\n" +
	"\x02ID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\bByUserID\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"=\n" +
	"\x10ByUserIDResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.shortener.ByUserIDR\x05items\"9\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users2\x8f\x04\n" +
	"\n" +
	"URLService\x12X\n" +
	"\x0fCreateURLRecord\x12!.shortener.CreateURLRecordRequest\x1a\".shortener.CreateURLRecordResponse\x12c\n" +
	"\x10CreateURLRecords\x12&.shortener.CreateURLRecordBatchRequest\x1a'.shortener.CreateURLRecordBatchResponse\x12N\n" +
	"\x10DeleteURLRecords\x12\".shortener.DeleteURLRecordsRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\rGetURLByShort\x12\x10.shortener.Short\x1a\x14.shortener.URLRecord\x12<\n" +
	"\x0eGetURLByUserID\x12\r.shortener.ID\x1a\x1b.shortener.ByUserIDResponse\x12=\n" +
	"\vPingContext\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x18.shortener.StatsResponseB3Z1github.com/atinyakov/go-url-shortener/proto;protob\x06proto3"

var (
	file_proto_shortener_proto_rawDescOnce sync.Once
	file_proto_shortener_proto_rawDescData []byte
)

func file_proto_shortener_proto_rawDescGZIP() []byte {
	file_proto_shortener_proto_rawDescOnce.Do(func() {
		file_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)))
	})
	return file_proto_shortener_proto_rawDescData
}

var file_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_shortener_proto_goTypes = []any{
	(*CreateURLRecordRequest)(nil),           // 0: shortener.CreateURLRecordRequest
	(*CreateURLRecordResponse)(nil),          // 1: shortener.CreateURLRecordResponse
	(*CreateURLRecordBatchRequestItem)(nil),  // 2: shortener.CreateURLRecordBatchRequestItem
	(*CreateURLRecordBatchResponceItem)(nil), // 3: shortener.CreateURLRecordBatchResponceItem
	(*CreateURLRecordBatchRequest)(nil),      // 4: shortener.CreateURLRecordBatchRequest
	(*CreateURLRecordBatchResponse)(nil),     // 5: shortener.CreateURLRecordBatchResponse
	(*URLRecord)(nil),                        // 6: shortener.URLRecord
	(*Short)(nil),                            // 7: shortener.Short
	(*DeleteURLRecordsRequest)(nil),          // 8: shortener.DeleteURLRecordsRequest
	(*ID)(nil),                               // 9: shortener.ID
	(*ByUserID)(nil),                         // 10: shortener.ByUserID
	(*ByUserIDResponse)(nil),                 // 11: shortener.ByUserIDResponse
	(*StatsResponse)(nil),                    // 12: shortener.StatsResponse
	(*emptypb.Empty)(nil),                    // 13: google.protobuf.Empty
}
var file_proto_shortener_proto_depIdxs = []int32{
	2,  // 0: shortener.CreateURLRecordBatchRequest.items:type_name -> shortener.CreateURLRecordBatchRequestItem
	3,  // 1: shortener.CreateURLRecordBatchResponse.items:type_name -> shortener.CreateURLRecordBatchResponceItem
	7,  // 2: shortener.DeleteURLRecordsRequest.items:type_name -> shortener.Short
	10, // 3: shortener.ByUserIDResponse.items:type_name -> shortener.ByUserID
	0,  // 4: shortener.URLService.CreateURLRecord:input_type -> shortener.CreateURLRecordRequest
	4,  // 5: shortener.URLService.CreateURLRecords:input_type -> shortener.CreateURLRecordBatchRequest
	8,  // 6: shortener.URLService.DeleteURLRecords:input_type -> shortener.DeleteURLRecordsRequest
	7,  // 7: shortener.URLService.GetURLByShort:input_type -> shortener.Short
	9,  // 8: shortener.URLService.GetURLByUserID:input_type -> shortener.ID
	13, // 9: shortener.URLService.PingContext:input_type -> google.protobuf.Empty
	13, // 10: shortener.URLService.GetStats:input_type -> google.protobuf.Empty
	1,  // 11: shortener.URLService.CreateURLRecord:output_type -> shortener.CreateURLRecordResponse
	5,  // 12: shortener.URLService.CreateURLRecords:output_type -> shortener.CreateURLRecordBatchResponse
	13, // 13: shortener.URLService.DeleteURLRecords:output_type -> google.protobuf.Empty
	6,  // 14: shortener.URLService.GetURLByShort:output_type -> shortener.URLRecord
	11, // 15: shortener.URLService.GetURLByUserID:output_type -> shortener.ByUserIDResponse
	13, // 16: shortener.URLService.PingContext:output_type -> google.protobuf.Empty
	12, // 17: shortener.URLService.GetStats:output_type -> shortener.StatsResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_shortener_proto_init() }
func file_proto_shortener_proto_init() {
	if File_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortener_proto_goTypes,
		DependencyIndexes: file_proto_shortener_proto_depIdxs,
		MessageInfos:      file_proto_shortener_proto_msgTypes,
	}.Build()
	File_proto_shortener_proto = out.File
	file_proto_shortener_proto_goTypes = nil
	file_proto_shortener_proto_depIdxs = nil
}
